[build]
command = "npm run build"
publish = "dist/client"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
external_node_modules = ["@nestjs/common", "@nestjs/core", "@nestjs/platform-express", "express", "postgres", "reflect-metadata", "rxjs", "serverless-http"]

[[redirects]]
from = "/sitemap.xml"
to = "/.netlify/functions/api/sitemap.xml"
status = 200

[[redirects]]
from = "/robots.txt"
to = "/.netlify/functions/api/robots.txt"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
